### ISSUE TITLE
History doesn't seem to work. Permission issue? 

### ISSUE THREAD

**Issue by turkeyphant** [TobiasPankner/Letterboxd-to-IMDb#12]
```
Traceback (most recent call last):                                                                                                
  File "/mnt/user/test/lb/letterboxd2imdb.py", line 248, in <module>
    main()
  File "/mnt/user/test/lb/letterboxd2imdb.py", line 229, in main
    with open(f'history/{current_files_hash}.txt', 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'history/760972372571e12806b2c8e5e49fb490.txt'
```

**Comment by TobiasPankner** [comment]
Hi, please try running the command with `-c`
