### ISSUE TITLE
Cant run letterboxd2imdb.py

### ISSUE THREAD

**Issue by samiam808** [TobiasPankner/Letterboxd-to-IMDb#5]
everything works until I do the run letterboxd2imdb.py step, i get this,

Traceback (most recent call last):
  File "C:\Users\samja\OneDrive\Desktop\Letterboxd to imdb\Letterboxd-to-IMDb-master\letterboxd2imdb.py", line 248, in <module>
    main()
  File "C:\Users\samja\OneDrive\Desktop\Letterboxd to imdb\Letterboxd-to-IMDb-master\letterboxd2imdb.py", line 173, in main
    current_files_hash = files_hash(['cookie.txt', args.zipfile])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samja\OneDrive\Desktop\Letterboxd to imdb\Letterboxd-to-IMDb-master\letterboxd2imdb.py", line 25, in files_hash
    with open(file, 'rb') as afile:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'letterboxd-samjakub-2023-04-10-18-34-utc.zip'

**Comment by TobiasPankner** [comment]
Have you created the cookie txt file?

**Comment by TobiasPankner** [comment]
And where did you download the zip file to?

**Comment by samiam808** [comment]
i moved the zip file to Letterboxd-to-IMDb-master foldler and it worked thanks!
